### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by Bchen0190** [mariohackandglitch/kartdlphax#10]
Hi,

Im am using a jp 3ds. I am getting "invalid plugin file Not a valid 3GX plugin format!@ Error Code :0xD8E07401" once I updated the new plugin file and open mario kart 7. Any idea how to fix it?

**Comment by PabloMK7** [comment]
Can you try redownloading the plugin file and the Luma 3gx plugin loader .firm? Maybe something corrupted.

**Comment by Bchen0190** [comment]
I tried redownloading both and am getting the same error

**Comment by PabloMK7** [comment]
Tested myself, the plugin is working perfectly. Make sure you don't have another plugin that is overriding kartdlphax. (For example, multiple 3GX files in `luma/plugins/0004000000030600`)
