### ISSUE TITLE
Not working in USA… fix anytime soon?

### ISSUE THREAD

**Issue by McMvffin** [mariohackandglitch/kartdlphax#11]
For whatever reason, when you use the xploit injection of the target device, it fails to load the green screen, and instead brings it to a black screen with lots of random colored dots. The target is on 11.17.0-50U, so please try and fix, cus my friend won’t stop bugging me lol. Thanks.

**Comment by McMvffin** [comment]
I am trying to use the other 2ds with cfw already on it. The target is a 2ds aswell.

**Comment by PlayerZwatcher** [comment]
i have the same issue as you, i spend like 4 hours trying and it didnt work

**Comment by PabloMK7** [comment]
It is currently not working on old 3ds. Still researching why.

**Comment by SirGamers** [comment]
1.17.0 broke it for USA O3DS/2DS but it works fine on a EUR/JPN O3DS/2DS and all N3DS/2DS

**Comment by McMvffin** [comment]
Alr.

**Comment by McMvffin** [comment]
I will keep looking for the update, good luck coding.

**Comment by PabloMK7** [comment]
Fixed in v1.3.2
