### ISSUE TITLE
Please, Please Support KOR MK7

### ISSUE THREAD

**Issue by raketaro** [mariohackandglitch/kartdlphax#6]
I have the Korean  NEW 2DS XL
Download version 1.2 and run the Korean version of Mario Kart 7(KOR MK7), but it says it is not compatible, please, please make the KOR MK7 compatible, the title ID is 00040000 00030A00

**Comment by SirGamers** [comment]
let me see if i could make a pr

**Comment by PabloMK7** [comment]
#12
