### ISSUE TITLE
Target 3DS freezes after trying to load ROP xPloit Injector on 11.17

### ISSUE THREAD

**Issue by H2KKI2** [mariohackandglitch/kartdlphax#8]
Having trouble on 11.17

After starting the match and loading the hax the target 3DS freezes, image below:

![ROP xPloit Injector Freeze](https://github.com/PabloMK7/kartdlphax/assets/36642902/45b67300-b7c1-48f3-8fd9-a791be16c71c)

**Comment by PabloMK7** [comment]
Fixed in 3b999a3dac0a824da5c9fd4294adea398f6ac373
https://github.com/PabloMK7/kartdlphax/releases/tag/v1.3.1
