### ISSUE TITLE
"A communication error has occurred" after selecting 'Create a Group' button

### ISSUE THREAD

**Issue by komododuck** [mariohackandglitch/kartdlphax#9]
Having a problem where after selecting the 'Create a Group' button in the local multiplayer menu, the screen fades to black followed by a "A communication error has occurred" error message. 

Including this information in case it helps:
The MK7 on the modded device is not updated, and the version of the device is 11.16 - while the version of the nonmodded device is 11.17.

**Comment by PabloMK7** [comment]
This could either be the network not enabled or the Mario kart 7 dump being bad

**Comment by komododuck** [comment]
Right - when you say network not enabled do you mean the wireless of the 3ds device not being switched on?

Thanks for the quick reply, I appreciate it.

**Comment by PabloMK7** [comment]
Yes that's what I mean.
(I'll be closing this issue as it's not related to kartdlphax itself. You can keep posting if you need more help)
